import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import Carousel from "../components/carousel/Carousel";
import Header from "../components/header/Navber";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Header></Header>
        <Carousel></Carousel>
        {children}
      </body>
    </html>
  );
}
